application: spicy-life
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /search.html
  static_files: static/search.html
  upload: static/search.html

- url: /home.html
  static_files: static/home.html
  upload: static/home.html


#- url: /(.*)
#  static_files: squadfree/\1
#  upload: squadfree/.*

- url: /search
  script: search.app

- url: /add
  script: main.app

- url: /rebuildIndex
  script: index.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
